language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r study-springboot2-webservice *
  - mkdir -p deploy
  - mv study-springboot2-webservice.zip deploy/study-springboot2-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: mihyun-springboot-build # s3 butcket
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip file 접근을 private 으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY
    bucket: mihyun-springboot-build
    key: study-springboot2-webservice.zip
    bundle_type: zip
    application: study-springboot2-webservice
    deployment_group: study-springboot2-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - mmhyun.lee@gmail.com

before_install:
  - chmod +x gradlew
